version: '3'
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - bootapp

  appservice:
    image: guitar-app
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/guitar_app?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=1234
    ports:
      - '8080:8080'
    networks:
      - bootapp

networks:
  bootapp:
    external: true